spring:
  mail:
    host: smtp.qq.com
    username: 335747019@qq.com
    password: jrrinlmdgfdrbiad
    from: 335747019@qq.com
    protocol: smtp
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.qq.com